version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "LukasPietzschmann"
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
        - "*"
